
env_args:
    # env: 'TicTacToe'
    #env: 'Geister'
    env: 'HungryGeese'
    #env: 'handyrl.envs.parallel_tictactoe'  # specify by path

train_args:
    turn_based_training: False
    observation: False
    gamma: 0.8
    forward_steps: 32
    compress_steps: 4
    entropy_regularization: 2.0e-3
    entropy_regularization_decay: 0.3
    update_episodes: 500
    batch_size: 400
    minimum_episodes: 10000
    maximum_episodes: 500000
    epochs: -1
    num_batchers: 7
    eval_rate: 0.1
    worker:
        num_parallel: 12
    lambda: 0.7
    policy_target: 'TD' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    eval:
        opponent:
            # - random
            # - rulebase  #
            - AgentBoilergoose  #
            - AgentCrazyGoose  #
            # - AgentGreedy
            # - AgentRiskAdverseGreedy
            - AgentPubHRL  #
            - AgentPubHRLLatest
            # - AgentSimpleBFS
            # - AgentSimpleToward
            - AgentStraightforwardBFS  #
    seed: 0
    restart_epoch: -1


worker_args:
    server_address: '10.140.0.3'  # THIS IS THE INTERNAL IP ADDRESS
    num_parallel: 64

